### ISSUE TITLE
Support Renames

### ISSUE THREAD

**Issue by travisennis** [hierynomus/smbj#48] opened 2017-05-23 18:09 UTC
It appears the library can support renames by using the SMB2SetInfoRequest class, but I'm having trouble figuring out how to configure an instance of that class that will successfully do the rename.

Could you give me some advice on how renames might be implemented? Also, could a rename method be implemented on the Share class, so that the API can hide the complexity of the SMB2SetInfoRequest from application code?

**Comment by hierynomus** [comment] 2017-05-23 19:06
Yes, the Share should abstract that away. There should be no need to
construct the messages yourself indeed. Will add it.

2017-05-23 20:09 GMT+02:00 Travis Ennis <notifications@github.com>:

**Comment by travisennis** [comment] 2017-05-24 13:27
Excellent! Thank you! Can you provide an estimate as to when you think it will get added and released?

**Comment by yin19941005** [comment] 2017-06-05 05:19
Hello,

I had created a pull request for this issue. I tried to move (rename) a "txt" file, empty directory and directory with a "txt" file and all of them passed on my environment. 

@travisennis , could you take a look and test with it?

**Comment by travisennis** [comment] 2017-06-06 12:47
@yin19941005, I did some testing with your code changes yesterday and everything worked in my environment as well.

**Comment by hierynomus** [comment] 2017-06-08 10:49
New PR for this is #61

**Comment by travisennis** [comment] 2017-06-08 18:53
@yin19941005 after further testing, I'm seeing an issue where your solution does not properly rename files or directories that exist inside of other directories.

**Comment by yin19941005** [comment] 2017-06-09 08:33
Hi @travisennis ,

Could you provide more details information? I am not able to reproduce the case you mentioned. I tested on my environment with the setup below : 

Client : Windows 10 PRO
Server : Windows Server 2008 R2
My test program is a modified version based on [`SmbjTest.java`](https://github.com/hierynomus/smbj/blob/master/src/it/java/SmbjTest.java) : 
```
...... (Skip irrelevant code)

            // Create directories
            share.mkdir(urlFix(writeTest_Path));
            share.mkdir(urlFix(writeTest_Path + "/1"));
            share.mkdir(urlFix(writeTest_Path + "/1/2"));
            share.mkdir(urlFix(writeTest_Path + "/1/2/3"));
            share.mkdir(urlFix(writeTest_Path + "/1/2/3/4"));
            share.mkdir(urlFix(writeTest_Path + "/2"));
            share.mkdir(urlFix(writeTest_Path + "/3"));
            share.mkdir(urlFix(writeTest_Path + "/4"));
            share.mkdir(urlFix(writeTest_Path + "/4/2"));
            share.mkdir(urlFix(writeTest_Path + "/4/2/3"));
            share.mkdir(urlFix(writeTest_Path + "/4/2/3/4"));

...... (Skip irrelevant code)

            // Writing another new file from here
            String javaTestFileName02 = "Testing002" + ".txt";
            String javaTestRemotePath02 = urlFix(writeTest_Path + "/1/" + javaTestFileName02);
            String javaTestText02 = "Testing 002 Testing 123 123";
            writeTestFile(share, javaTestRemotePath02, javaTestText02);

            // Testing for rename file
            String javaTestChangeFileName02 = urlFix(writeTest_Path + "/4/2/3/4/" + "Testing002_01" + ".txt");
            com.hierynomus.smbj.share.File renameFile = share.openFile(javaTestRemotePath02, EnumSet.of(AccessMask.DELETE, AccessMask.GENERIC_WRITE), SMB2CreateDisposition.FILE_OPEN);
            renameFile.rename(javaTestChangeFileName02);
            renameFile.close();

            // Upload 2 files for further rename testing
            String renameTestFile01 = UUID.randomUUID().toString() + ".txt";
            String renameTestFile02 = UUID.randomUUID().toString() + ".txt";
            InputStream renameTargetStream001 = new FileInputStream(initialFile001);
            InputStream renameTargetStream002 = new FileInputStream(initialFile002);
            write(share, urlFix(writeTest_Path + "/4/2/3/4/" + file01), renameTargetStream001);
            write(share, urlFix(writeTest_Path + "/4/2/3/4/" + file02), renameTargetStream002);

            // Testing for rename directory
            String originalDirectoryName = urlFix(writeTest_Path + "/4/2/3");
            String targetDirectoryName = urlFix(writeTest_Path2 + "/4");
            com.hierynomus.smbj.share.Directory renameDirectory = share.openDirectory(originalDirectoryName, EnumSet.of(AccessMask.DELETE, AccessMask.GENERIC_WRITE), null, SMB2CreateDisposition.FILE_OPEN);
            renameDirectory.rename(targetDirectoryName);
            renameDirectory.close();

            // Try to random access file the renamed file
            com.hierynomus.smbj.share.File randomAccess = share.openFile(urlFix(writeTest_Path2 + "/4/4/" + "Testing002_01" + ".txt"),
                EnumSet.of(AccessMask.GENERIC_READ, AccessMask.GENERIC_WRITE), SMB2CreateDisposition.FILE_OPEN);
            byte[] readbuffer = new byte[255];
            randomAccess.read(readbuffer, 2, 25);
            String readString = new String (readbuffer, "UTF8");
            System.out.printf( readString + "\n");
            String writeSampleTest = System.getProperty("line.separator") + "Testing 123 123";
            byte[] writebuffer = writeSampleTest.getBytes();
            randomAccess.write(writebuffer, 27, writebuffer.length);
            randomAccess.close();
```

The write functions called on the above code : 
```
    // write function to call
    void write(DiskShare share, String remotePath, String localResource)
            throws IOException, SMBApiException {
        // logger.debug("Writing {}, {} to {}", localResource, this.getClass().getResource(localResource), remotePath);
        System.out.printf("Writing {}, {} to {} \n", localResource, this.getClass().getResource(localResource), remotePath);
        com.hierynomus.smbj.share.File file = share.openFile(remotePath,
                EnumSet.of(AccessMask.GENERIC_WRITE), SMB2CreateDisposition.FILE_OVERWRITE_IF);
        try (InputStream is = this.getClass().getResourceAsStream(localResource)) {
            file.write(new InputStreamByteChunkProvider(is));
        }
        file.close();
    }

    static void write(DiskShare share, String remotePath, InputStream is)
            throws IOException, SMBApiException {
        com.hierynomus.smbj.share.File file = share.openFile(remotePath,
                EnumSet.of(AccessMask.GENERIC_WRITE), SMB2CreateDisposition.FILE_OVERWRITE_IF);
        file.write(new InputStreamByteChunkProvider(is));
        file.close();
    }

    static void writeTestFile(DiskShare share, String remotePath, String inputString)
        throws IOException, SMBApiException {
        InputStream StringTextStream = new ByteArrayInputStream(inputString.getBytes());
        com.hierynomus.smbj.share.File file = share.openFile(remotePath,
            EnumSet.of(AccessMask.GENERIC_WRITE), SMB2CreateDisposition.FILE_OVERWRITE_IF);
        file.write(new InputStreamByteChunkProvider(StringTextStream));
        file.close();
    }
```

<br>
The renamed file screen capture : 

![renamesuccess001](https://user-images.githubusercontent.com/23186757/26967464-ec12f590-4d30-11e7-9ab2-f03648d42380.png)
![renamesuccess002](https://user-images.githubusercontent.com/23186757/26967468-ef9a96fa-4d30-11e7-84de-955a9228aa3a.png)

**Comment by travisennis** [comment] 2017-06-09 18:13
@yin19941005 it appears I didn't have all of your most recent changes pulled down. Now that I'm working with the most current code, renames seem to be working fine. I apologize for the confusion.

**Comment by hierynomus** [comment] 2017-06-09 18:52
#61 is merged. So Iwill close this issue.

**Closed by hierynomus** 2017-06-09 18:52 UTC
Labels: enhancement

**Comment by pepijnve** [comment] 2017-06-12 07:04
@yin19941005 [MS-FSCC] states
> RootDirectory (4 bytes): A 32-bit unsigned integer that contains the file handle for the directory to which the new name of the file is relative. For network operations, this value MUST be zero.
Does `network operations` mean it applies to any SMB based rename operation? If so, I don't think it makes sense to allow the `rootDirectory` value to be set. Perhaps the overload of `rename` that provides that parameter should be removed?

**Comment by yin19941005** [comment] 2017-06-12 07:42
Hi @pepijnve ,

Actually, I am not sure about the meaning on the [MS-FSCC] document ([`2.4.34.2 FileRenameInformation for SMB2`](https://msdn.microsoft.com/en-us/library/cc704597.aspx)). It's header states the document is only for SMB2 and it should simply saying something like `It MUST be zero.` without any condition. 

However, it states : 

> For network operations, this value MUST be zero.

This confused me, so I just leave it able to set in the code. I tends to believe your opinion, the `network operations` should applies to all SMB rename operation. For me, I didn't try to use for the `rootDirectory` parameter. I just simply set it to zero.

@hierynomus ,what do you think about it?
