### ISSUE TITLE
com.hierynomus.mssmb2.SMBApiException: STATUS_DIRECTORY_NOT_EMPTY (0xc0000101):

### ISSUE THREAD

**Issue by fiasko131** [hierynomus/smbj#445] opened 2019-03-21 18:45 UTC
I'm trying to delete a folder recursively. Here is the code I use:
````java
private void deleteRecursiveSmb(SmbItem smbItemSrc,String src){
	try {
                if (smbItemSrc.getDiskShare().folderExists(src)){
                    emptyFolderToRemove.add(src);
                    Log.i("deleteSmb20",src);
                    for (FileIdBothDirectoryInformation f : smbItemSrc.getDiskShare().list(src)) {
                        String filename = f.getFileName();
                        if (".".equals(filename) || "..".equals(filename)) {
                            continue;
                        }
                        String src1 = src+"\\"+filename;
                        Log.i("deleteSmb21",src1);
                        deleteRecursiveSmb(smbItemSrc,src1);

                    }

                }else {
                    
                    smbItemSrc.getDiskShare().rm(src);
                    activityReference.get().listSmb2Files.remove(smbItemSrc);
                    updateSmb = true;
                    publishProgress();
                }

          }catch (final SMBApiException e){
                e.printStackTrace();
          }
    }
````
The method works perfectly but I still have to delete the directories left empty. For that I fill a list with the paths of the directories to erase once they are empty.
````java
for (String path : emptyFolderToRemove){
        if (iFo.getSmbItem().getDiskShare().folderExists(path)){
               iFo.getSmbItem().getDiskShare().rmdir(path,true);
        }          
}
````
This is where I get this execption while the directories in question are empty in my explorer ??

> com.hierynomus.mssmb2.SMBApiException: STATUS_DIRECTORY_NOT_EMPTY (0xc0000101): SetInfo failed for SMB2FileId{persistentHandle=c7 1a 00 00 1b 00 00 00}

What am I doing wrong?

**Comment by ecki** [comment] 2019-03-21 19:52
You need to delete the deepest directory first. Instead of adding the Dir to a list you can do it after your list loop on `src`:

    ...
                Log.i("deleteSmb21",src1);
                 deleteRecursiveSmb(smbItemSrc,src1);
             } // for
             smbItemSrc.getDiskShare().rmdir(src, true); // <==
        }else {
            smbItemSrc.getDiskShare().rm(src);
    ...

**Comment by hierynomus** [comment] 2019-03-21 22:13
@ecki is right. But instead of changing the logic, you can use a Stack instead of a List, which gives LIFO semantics instead of FIFO.

**Comment by fiasko131** [comment] 2019-03-22 08:18
@ecki is just logic!! thanks

**Comment by fiasko131** [comment] 2019-03-26 17:26
In fact I always have the same issue with @ecki solution, and Dir is really empty :

> com.hierynomus.mssmb2.SMBApiException: STATUS_DIRECTORY_NOT_EMPTY (0xc0000101): SetInfo failed for SMB2FileId{persistentHandle=cb 00 00 00 1d 00 00 00}

What means :  SetInfo failed for SMB2FileId{persistentHandle=cb 00 00 00 1d 00 00 00}

**Comment by ecki** [comment] 2019-03-26 17:26
Is something missing?

(BTW I understand that smbj wants to be a low level library, but maybe we can add a companion project with some common functions like deleting whole directory trees? Or should we at least add it as example code?)

**Comment by hierynomus** [comment] 2019-03-26 20:05
Did you have a look at `DiskShare.rmdir(String path, boolean recursive)`? Setting the `recursive` to true will delete the entire tree.

**Comment by fiasko131** [comment] 2019-03-27 11:58
@hierynomus  
I tried with recursive set to true and false: same issue.
the issue is not systematic sometimes dirs are deleted correctly.
I work on Android in an asyncTask.

@ecki 
There are no hidden files in folders.
> com.hierynomus.mssmb2.SMBApiException: STATUS_DIRECTORY_NOT_EMPTY (0xc0000101): SetInfo failed for SMB2FileId{persistentHandle=c7 1a 00 00 1b 00 00 00}
	at com.hierynomus.smbj.share.Share.receive(Share.java:366)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:346)
	at com.hierynomus.smbj.share.Share.setInfo(Share.java:198)
	at com.hierynomus.smbj.share.DiskShare.setFileInformation(DiskShare.java:296)
	at com.hierynomus.smbj.share.DiskShare.deleteOnClose(DiskShare.java:386)
	at com.hierynomus.smbj.share.DiskEntry.deleteOnClose(DiskEntry.java:178)
	at com.hierynomus.smbj.share.DiskShare.rmdir(DiskShare.java:364)
	at com.hierynomus.smbj.share.DiskShare.rmdir(DiskShare.java:354)
	at com.techniwork.fileUtils.DeleteTask$override.doInBackground(DeleteTask.java:94)
	at com.techniwork.fileUtils.DeleteTask$override.access$dispatch(Unknown Source:211)
	at com.techniwork.fileUtils.DeleteTask.doInBackground(DeleteTask.java:0)
	at com.techniwork.fileUtils.DeleteTask.doInBackground(DeleteTask.java:43)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by Lampros7** [comment] 2019-07-24 13:21
Any updates about this from anyone?
I seem to be experiencing the same randomness of this issue as @fiasko131  where certain folders might or might not get deleted.
Thanks in advance

**Comment by zerikv** [comment] 2019-08-06 12:08
Same issue and same stack when I use `DiskShare.rmdir(String path, boolean recursive)`.
The cause for me it was that among the deleted entries there was some `DiskEntry` previously opened with the same `DiskShare` and not closed.
I think you should search calls to `open()` and `openFile()` on the DiskShare and check that all are enclosed for example in a try-with-resources block or properly closed in a finally.
And for `com.hierynomus.smbj.share.File` be aware that the streams (returned by `getInputStream()` and `getOutputStream()`) don't close the `File` (it was my mistake).
Otherwise one ugly workaround could be to close and reopen the `DiskShare` before to execute the recursive rmdir.

**Comment by hierynomus** [comment] 2023-07-10 07:45
Indeed, InputStream and OutputStream don't close the underlying file, simply because you manually opened the `File`, it's not under control of the streams.

As for this issue, I'll close it, as the suggestions in the thread indeed are the solution.

**Closed by hierynomus** 2023-07-10 07:45 UTC
