### ISSUE TITLE
this android studio cannot be compiled? I want this app apk and look is whatｉwant

### ISSUE THREAD

**Issue by huanyuan** [hierynomus/smbj#471] opened 2019-05-29 02:27 UTC
![image](https://user-images.githubusercontent.com/12406954/58524582-466f8980-81fb-11e9-8b15-64253533236c.png)

**Comment by hierynomus** [comment] 2019-05-29 08:02
I'm not sure what the problem is but it doesn't seem to be with the library

**Comment by huanyuan** [comment] 2019-05-29 08:22
![image](https://user-images.githubusercontent.com/12406954/58541253-a97a1400-822d-11e9-96b5-fdea413c891e.png)
what the library? I have no change this project after i download it

**Comment by hierynomus** [comment] 2019-05-29 09:40
I have no idea what you're trying to achieve. The project is already available on Maven Central to be used as a library inside an Android application that you can build.

**Comment by ivarprudnikov** [comment] 2019-05-30 12:20
@huanyuan if you want to add `smbj` to Android project, specify dependency in your _app_ `build.gradle`

```
dependencies {
    ...
    implementation 'com.hierynomus:smbj:0.9.1'
    ...
}
```

**Comment by hierynomus** [comment] 2019-10-16 10:18
Closing this issue, @ivarprudnikov supplied your answer.

**Closed by hierynomus** 2019-10-16 10:18 UTC
