### ISSUE TITLE
java.lang.VerifyError: com/hierynomus/smbj/auth/SpnegoAuthenticator

### ISSUE THREAD

**Issue by yoosYyd** [hierynomus/smbj#231] opened 2017-11-01 14:37 UTC
What may be wrong ?

`dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile files('libs/slf4j-api-1.7.25.jar')
    compile files('libs/mbassador-1.3.0.jar')
    compile files('libs/bcprov-jdk15on-1.57.jar')
    compile files('libs/bctls-jdk15on-1.58.0.0.jar')
    compile files('libs/smbj-0.5.0.jar')
}`

`java.lang.VerifyError: com/hierynomus/smbj/auth/SpnegoAuthenticator
                                                     at com.hierynomus.smbj.auth.SpnegoAuthenticator$Factory.create(SpnegoAuthenticator.java:51)
                                                     at com.hierynomus.smbj.auth.SpnegoAuthenticator$Factory.create(SpnegoAuthenticator.java:41)
                                                     at com.hierynomus.smbj.connection.Connection.getAuthenticator(Connection.java:220)
                                                     at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:159)
                                                     at com.yda.user.sambaa.MainActivity$SAMBAShell.Connect(MainActivity.java:40)
                                                     at com.yda.user.sambaa.MainActivity$SAMBAShell.run(MainActivity.java:55)
                                                     at java.lang.Thread.run(Thread.java:841)`

**Comment by hierynomus** [comment] 2017-11-04 14:38
java.lang.VerifyError can be the result when you have compiled against a different library than you are using at runtime.

Try doing a full clean rebuild.

**Comment by hierynomus** [comment] 2017-11-07 21:21
@yoosYyd Do you need more help with this?

**Comment by yoosYyd** [comment] 2017-11-08 07:51
Yes.Rebuild can't help for that problem.I use IDE  - "Android Studio".

**Comment by hierynomus** [comment] 2017-11-08 10:04
Have you done research on Google? This is not an SMBJ problem, but hints at a problem in the use in Android.

**Comment by yoosYyd** [comment] 2017-11-09 20:42
Your lib not compatible with Android ?

**Comment by hierynomus** [comment] 2017-11-10 14:37
@yoosYyd Googling turned up this result: https://stackoverflow.com/questions/668788/android-java-lang-verifyerror

**Comment by hierynomus** [comment] 2017-11-14 10:05
@yoosYyd Do you need more help with this, or did the Stackoverflow link help you find the answer?

**Comment by yoosYyd** [comment] 2017-11-14 11:24
No, this link can't help me.But,I found that this problem exist only on Android 19 API.

**Comment by hierynomus** [comment] 2017-11-14 12:19
Do you need more help with this? If so, what is the full logging output before you get the VerifyError?

**Comment by yoosYyd** [comment] 2017-11-15 17:25
Full logcat errorlog - https://pastebin.com/kNvVZBxY

**Comment by shettychethan4** [comment] 2017-11-22 12:30
@yoosYyd  Did you find the solution ? if yes let me know man.

**Comment by pepijnve** [comment] 2017-11-22 12:40
You're getting a VerifyError on `SpnegoAuthenticator`. That class depends on `org.ietf.jgss` which is part of Java SE, but is not available out of the box on Android. Could that be the cause of the issue?

The set of authenticators in the default SmbConfig is set up using `.withAuthenticators(new SpnegoAuthenticator.Factory(), new NtlmAuthenticator.Factory())`. You could try calling `withAuthenticators(new NtlmAuthenticator.Factory())` on your SmbConfig object to avoid triggering the GSSAPI dependent code.

**Comment by hierynomus** [comment] 2017-11-22 20:53
@pepijnve Thanks for thinking along, that might indeed be it. @yoosYyd, can you check?

**Comment by yoosYyd** [comment] 2017-11-24 19:52
> That class depends on org.ietf.jgss which is part of Java SE, but is not available out of the box on Android. Could that be the cause of the issue?
You right.

**Comment by hierynomus** [comment] 2017-11-24 20:28
Ok, closing this issue :)

**Closed by hierynomus** 2017-11-24 20:28 UTC
