### ISSUE TITLE
Unable to connect.

### ISSUE THREAD

**Issue by ramreddy77** [hierynomus/smbj#167] opened 2017-08-24 05:57 UTC
Connection connection = client.connect("10.0.2.179");
Unable to connect to the ip address. Can you please help me.

INFO  2017-08-24 11:18:04,001 [Packet Reader for 10.0.2.179] com.hierynomus.smbj.transport.PacketReader: PacketReader error.
INFO  2017-08-24 11:18:04,001 [Packet Reader for 10.0.2.179] com.hierynomus.smbj.connection.Connection: Closed connection to 10.0.2.179

**Comment by hierynomus** [comment] 2017-08-24 06:17
Duplicate of #168

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2017-08-24 06:16 UTC
