### ISSUE TITLE
I want to pass file input stream from smbj file object to copy a file from one server to other server

### ISSUE THREAD

**Issue by harisingh-highq** [hierynomus/smbj#336] opened 2018-06-06 08:30 UTC
@hierynomus 
I have tried with below code to return input stream of smbj file object
```
public InputStream readUploadedFile(String destinationFile,String filePath,Integer encryptionFlag, String encryptedSitekey) throws RepositorySpecificException,ClientAbortException,Exception {
		Session session = null;
		DiskShare share;
		com.hierynomus.smbj.share.File smbFileRead =null;
		InputStream is = null;
		try(Connection connection=getSmbjRepoConn()) {
			try
			{
				session = getSmbjConnectionSession(connection);
				share = getSmbjSharedDirectoryConnection(session);
				
				Map<String,String> mapParam=repDBO.getParams();
				String repConnString = mapParam.get(HybridConstants.SMBJ_RESOURCE_DIRECTORY);
				repConnString = checkFolderPath(repConnString);
				filePath = checkFolderPath(filePath);
				repConnString=repConnString+filePath;
				String fileName = repConnString + destinationFile;
				
				if(share.fileExists(fileName)){
					try {
						smbFileRead = share.openFile(fileName, EnumSet.of(AccessMask.GENERIC_READ), null, SMB2ShareAccess.ALL,
								SMB2CreateDisposition.FILE_OPEN, null);
						is = smbFileRead.getInputStream();
					}
					catch(Exception e) {
						
					}
				}
			}catch(Exception ex)
			{
				
			}
		}
		return is;
	}
```

If i pass that stream to other server method, it is throwing below error stack trace:-
`Caused by: com.hierynomus.smbj.common.SMBRuntimeException: DiskShare has already been closed
	at com.hierynomus.smbj.share.Share.send(Share.java:327)
	at com.hierynomus.smbj.share.Share.readAsync(Share.java:220)
	at com.hierynomus.smbj.share.File.readAsync(File.java:131)
	at com.hierynomus.smbj.share.FileInputStream.sendRequest(FileInputStream.java:145)
	at com.hierynomus.smbj.share.FileInputStream.loadBuffer(FileInputStream.java:118)
	at com.hierynomus.smbj.share.FileInputStream.read(FileInputStream.java:73)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Unknown Source)
	at com.hybridintegration.repository.JCIFSRepo.writeToJCIFSPlainStream(JCIFSRepo.java:2963)
	at com.hybridintegration.repository.JCIFSRepo.uploadFile(JCIFSRepo.java:350)
	... 7 more
`
I found the root cause of that due to connection and share object closed while returning stream from above method but if i will not close the connection then it remains to opening.
So can you please help me to return stream from smbj file object with closing the connection?

**Comment by pepijnve** [comment] 2018-06-06 08:42
This isn't really the appropriate place to ask basic Java programming questions, but ok...

You're code is explicitly closing the connection because you're using try-with-resources.

```
try(Connection connection=getSmbjRepoConn()) {
   ...
}
```

If you don't want the connection to be closed, don't use try-with-resources.

If you want the connection to be closed once the InputStream is closed, make a wrapper FilterInputStream subclass that also calls connection.close() when close is invoked.
Alternatively, you can pass a `Consumer<InputStream>` parameter to your `readUploadedFile` function and invoke that inside the try-with-resources block.

**Closed** 2018-06-06 08:44 UTC

**Comment by harisingh-highq** [comment] 2018-06-06 10:13
Hi @pepijnve 

> I found the root cause of that due to connection and share object closed while returning stream from above method but if i will not close the connection then it remains to opening.

I have already mentioned the root cause here
But my concern is that if i remove try-with-resources to stop closing the connection then it will copy the file successfully
But if i retry to upload same file on same location then it is throwing below exception:-
Exception detail :STATUS_SHARING_VIOLATION(3221225539/3221225539): Create failed for collab_4_1_4\SMBJ_Repo_Group3\\griffin\2016\sitedocs\\hqhybrid.txt

**Cause- Due to removing of try-with-resources connection not being closed** 

So now i want a kind of solution which should copy file successfully and also if i retry to upload same file on same path, it should not give above error means connection should be closed internally.
So is there any alternative solution for that issue?

**Comment by pepijnve** [comment] 2018-06-06 11:10
Yes this can be solved; see my suggestions above. In short, structure your code in a different way so that this is no longer an issue. BTW the problem is not the connection that's being held open but the File (`smbFileRead`).

The absolute simplest solution for you would be to remove the try-with-resources and return
```
new FilterInputStream(is) {
    @Override
    public void close() throws IOException
    {
        super.close();
        smbFileRead.close();
        connection.close();
    }
}
```

or something along those lines.
