### ISSUE TITLE
DFS resolution redundancy

### ISSUE THREAD

**Issue by zsoltm** [hierynomus/smbj#498] opened 2019-10-03 07:47 UTC
I have a performance issue. Likely it's a feature request. I'm using SMBJ to copy a bunch of files to a DFS enabled share. 

I have a loop like this:

```java
for (Path sourcePath: sourcePaths) {
    final targetPath = BACKSLASH_JOINER.join(targetRoot, sourcePath.getFileName());
    try (com.hierynomus.smbj.share.File file = share.openFile(targetPath,
            EnumSet.of(AccessMask.GENERIC_ALL), null, SMB2ShareAccess.ALL, FILE_CREATE, null);
            OutputStream shareOutStream = file.getOutputStream(false)) {
        Files.copy(sourcePath, shareOutStream);
    }
}
```

With this code DFS resolution is performed by SMBJ for each file, but it always resolves to the same host and share in this case as I'm writing to the same target folder, so it's completely redundant.

I'd like to avoid these steps:

+ an extra DFS resolution;
+ connection / auth / etc to the same server for each file.

These are big performance hit especially when the remote host is slow or there is a network latency as in my case the: share is on a different continent.

I'd expect that somehow I can open a `Directory` for writing, and re-use it within the loop instead of specifying a string path which gets resolved each time. Or perhaps an API call where I could provide a pre-resolved path.

**Comment by andershermansen** [comment] 2019-10-04 09:50
Dupe of #406 ? Check the information in that issue.

**Comment by zsoltm** [comment] 2019-10-04 15:51
> Dupe of #406 ? Check the information in that issue.

Indeed it is, thanks for the heads up. I quickly created another PR based on yours, with some locking added to avoid lost sessions in a possible race condition.

**Comment by andershermansen** [comment] 2019-10-04 18:24
> > Dupe of #406 ? Check the information in that issue.
> 
> Indeed it is, thanks for the heads up. I quickly created another PR based on yours, with some locking added to avoid lost sessions in a possible race condition.

Cool. I see if I can manage to test it on our setup.

**Closed** 2020-11-10 14:20 UTC
