### ISSUE TITLE
com.hierynomus.mssmb2.SMBApiException: UNKNOWN(4294967295/3221225569)

### ISSUE THREAD

**Issue by Murugesh-Murugesh** [hierynomus/smbj#357] opened 2018-07-16 08:40 UTC
Hello all,
I tried to read file from share and get the followed exception

com.hierynomus.mssmb2.SMBApiException: UNKNOWN(4294967295/3221225569): Create failed for tmp2/test.txt
	at com.hierynomus.smbj.share.Share.receive(Share.java:335)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:319)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:134)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:96)

Can you explain, What is here the problem?
What mean the UNKNOWN(4294967295/3221225569) Error?
What can be feasible fix?

**Comment by pepijnve** [comment] 2018-07-16 08:49
I'm going to create a PR to make this more easy to interpret. The error code in question here is 3221225569 or 0xC0000061. You can find all of these a listing of all possible error codes at https://msdn.microsoft.com/en-us/library/cc704588.aspx.

Unfortunately, a lot of them require some experience to interpret. This one is `STATUS_PRIVILEGE_NOT_HELD` which means

> A required privilege is not held by the client.

It's a type of permission/access denied error that can be caused by many things, but essentially you're trying to perform an operation and the target server is not allowing it. A useful debugging strategy for this is to simplify the operations you're doing so that they succeed and then add bits back one by one until it fails. For instance, reduce the desired access set down to just FILE_READ_DATA or something minimal like that and add desired access bits until the operation fails.

Some possible other possible examples:
- Trying to open the file with the `FILE_OPEN_FOR_BACKUP_INTENT` and the user account you're using is not a member of the necessary groups that grant this privilege (which are server implementation specific btw).
- Trying to open files with `WRITE_OWNER` without `FILE_OPEN_FOR_BACKUP_INTENT`.
- Trying to open files with `ACCESS_SYSTEM_SECURITY` without an administrator or backup account.
- ...

**Comment by hierynomus** [comment] 2018-07-17 11:04
@Murugesh-Murugesh Did @pepijnve answer your question? I've merged PR #358 which adds the specific status to the NtStatus enumeration. If you have no more questions, please close the issue.

**Comment by hierynomus** [comment] 2018-07-26 07:17
Closing this issue as the extra status code has been released.

**Closed by hierynomus** 2018-07-26 07:17 UTC
