### ISSUE TITLE
Anonymous user not working for SMBv2

### ISSUE THREAD

**Issue by debarghya85** [hierynomus/smbj#216] opened 2017-10-12 11:18 UTC
Code:
---------
```
AuthenticationContext authContext = null;
if(!username.trim().equals(""))
	authContext = new AuthenticationContext(username, password.toCharArray(), domain);
else
	authContext = AuthenticationContext.anonymous();

try {
    Session session = connection.authenticate(authContext);
    DiskShare share = (DiskShare) session.connectShare(sambaSharedPath); // giving exception in this line
}catch(Exception ex){
	ex.printStackTrace();
}
```

This is the exception trace:
--------------------------------
```
com.hierynomus.smbj.common.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Could not connect to [Share_Location]
	at com.hierynomus.smbj.session.Session.connectTree(Session.java:102)
	at com.hierynomus.smbj.session.Session.connectShare(Session.java:87)
```	
	
	
Details log:
------------------
```
[main] INFO com.hierynomus.protocol.commons.socket.ProxySocketFactory - Connecting to Share_IP/Port
[main] INFO com.hierynomus.smbj.transport.PacketReader - Starting PacketReader on thread: Packet Reader for Share_IP
[main] INFO com.hierynomus.smbj.connection.Connection - Negotiating dialects [SMB_2_0_2, SMB_2_1] with server Share_IP
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 1) credits to SMB2_NEGOTIATE with message id << 0 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_NEGOTIATE with message id << 0 >>
[Packet Reader for Share_IP] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_NEGOTIATE with message id << 0 >>
[Packet Reader for Share_IP] INFO com.hierynomus.smbj.connection.Connection - Server granted us 1 credits for SMB2_NEGOTIATE with message id << 0 >>, now available: 1 credits
[main] INFO com.hierynomus.smbj.connection.Connection - Negotiated the following connection settings: ConnectionInfo{
  serverGuid=serverGuid,
  serverName='Share_IP',
  negotiatedProtocol=NegotiatedProtocol{dialect=SMB_2_1, maxTransactSize=1048576, maxReadSize=1048576, maxWriteSize=1048576},
  clientGuid=clientGuid,
  clientCapabilities=null,
  serverCapabilities=[SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_LARGE_MTU],
  clientSecurityMode=0,
  serverSecurityMode=1,
  server='null'
}
[main] INFO com.hierynomus.smbj.connection.Connection - Successfully connected to: Share_IP
[main] INFO com.hierynomus.smbj.auth.NtlmAuthenticator - Initialized Authentication of  using NTLM
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 1 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_SESSION_SETUP with message id << 1 >>
[Packet Reader for Share_IP] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_SESSION_SETUP with message id << 1 >>
[Packet Reader for Share_IP] INFO com.hierynomus.smbj.connection.Connection - Server granted us 1 credits for SMB2_SESSION_SETUP with message id << 1 >>, now available: 1 credits
[main] INFO com.hierynomus.smbj.connection.Connection - More processing required for authentication of  using com.hierynomus.smbj.auth.NtlmAuthenticator@2fc2534f
[main] INFO com.hierynomus.smbj.auth.NtlmAuthenticator - Received token: a1 81 96 30 81 93 a0 03 0a 01 01 a1 0c 06 0a 2b 06 01 04 01 82 37 02 02 0a a2 7e 04 7c 4e 54 4c 4d 53 53 50 00 02 00 00 00 0c 00 0c 00 30 00 00 00 15 82 8a e0 f5 d2 c5 10 14 13 3d 58 00 00 00 00 00 00 00 00 40 00 40 00 3c 00 00 00 43 00 45 00 4e 00 54 00 4f 00 53 00 02 00 0c 00 43 00 45 00 4e 00 54 00 4f 00 53 00 01 00 0c 00 43 00 45 00 4e 00 54 00 4f 00 53 00 04 00 00 00 03 00 14 00 67 00 6f 00 6f 00 67 00 6c 00 65 00 61 00 70 00 70 00 73 00 00 00 00 00
[main] INFO com.hierynomus.smbj.auth.NtlmAuthenticator - Received NTLM challenge from: CENTOS
com.hierynomus.smbj.common.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Could not connect to \\Share_IP\ShareFolderWithAnonymousAccess[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 2 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_SESSION_SETUP with message id << 2 >>
[Packet Reader for Share_IP] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_SESSION_SETUP with message id << 2 >>
[Packet Reader for Share_IP] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_SESSION_SETUP with message id << 2 >>, now available: 33 credits
[main] INFO com.hierynomus.smbj.connection.Connection - Successfully authenticated  on Share_IP, session is 164396731
[main] INFO com.hierynomus.smbj.session.Session - Connecting to \\Share_IP\ShareFolderWithAnonymousAccess on session 164396731
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 33) credits to SMB2_TREE_CONNECT with message id << 3 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_TREE_CONNECT with message id << 3 >>
[Packet Reader for Share_IP] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_TREE_CONNECT with message id << 3 >>
[Packet Reader for Share_IP] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_TREE_CONNECT with message id << 3 >>, now available: 65 credits
[Packet Reader for Share_IP] ERROR com.hierynomus.smbj.session.PacketSignatory - Signatures for packet SMB2_TREE_CONNECT with message id << 3 >> do not match (received: [102, 42, 37, 4, -72, 14, -20, 14, -118, 97, 106, -5, -119, -7, 125, -81], calculated: [-89, 42, -27, 11, 74, -56, -6, -96, 87, 124, -6, -68, 15, -38, 86, -107, -71, 88, 55, 88, 92, -62, 52, 116, 106, -84, 68, -88, 126, -17, -27, 17])
[Packet Reader for Share_IP] WARN com.hierynomus.smbj.connection.Connection - Invalid packet signature for packet SMB2_TREE_CONNECT with message id << 3 >>
[main] INFO com.hierynomus.smbj.session.Session - dialect=null, creditCharge=1, creditRequest=0, creditResponse=33, message=SMB2_TREE_CONNECT, messageId=3, asyncId=0, sessionId=164396731, treeId=0, status=STATUS_ACCESS_DENIED, statusCode=3221225506, flags=9, nextCommandOffset=0
```

**Comment by gidravlic** [comment] 2017-10-12 11:30
> 
```java
DiskShare share = (DiskShare) session.connectShare(sambaSharedPath); // giving exception in this line
```

You MUST use share name instead share path. If you have MyShare\MyPath, you code will be:
```java
DiskShare share = (DiskShare) session.connectShare(MyShare);
```
and after work with your path MyPath

**Comment by hierynomus** [comment] 2017-10-12 12:04
Nope, I don't think that's the problem @gidravlic. The problem is that the authenticated user ('anonymous') has no access to the given share. Check whether you've enabled guest access on the share. The user is correctly authenticated as you have a session.

**Comment by debarghya85** [comment] 2017-10-12 12:15
sharepath is the variable name.. actually value is only share folder name.

**Comment by hierynomus** [comment] 2017-10-13 12:06
@debarghya85 Have you tried to use the `AuthenticationContext.guest()` credentials?

**Comment by debarghya85** [comment] 2017-10-13 13:36
No. I have not tried. Will try and let you know on 16th oct. But is guest
work as anonymous. In guest i found that username is guest.

**Comment by hierynomus** [comment] 2017-10-13 13:50
THey're 2 different concepts indeed. And they are thus also different in what they can access.

**Comment by debarghya85** [comment] 2017-10-16 05:13
No its not working for guest as well. Same error is given by SMBJ. Also I need Anonymous access, not the guest access.

**Comment by hierynomus** [comment] 2017-10-16 12:44
Can you capture a TCP dump from the windows attempt to connect to the share, and the SMBJ attempt? ANalyzing those should point to where they're different.

**Comment by debarghya85** [comment] 2017-10-17 04:38
for Windows also smbj is not working for anonymous. But its(anonymous access) working for SMBv1 with jcifs library.

**Comment by Varsha-Nagarajan** [comment] 2017-10-17 07:16
I have a samba server setup on linux and on that both guest and anonymous authentication is working fine with the latest release of smbj. Maybe your share has not been configured properly. Could you additionally share that configurations you used to set up the share?

**Comment by debarghya85** [comment] 2017-10-17 08:22
@Varsha-Nagarajan , Can you please inform what are the things to do while configuring in linux to support anonymous auth?

**Comment by Varsha-Nagarajan** [comment] 2017-10-17 10:47
My smb.conf looks like below:

[content-repo]
        browseable = yes
        path = <path to repo>
        guest ok = yes
        read only = yes
        public = yes
        available = yes

Also, under [global] we need to provide : 
 usershare allow guests = Yes
 max protocol = SMB2  --> needed for sles11 boxes but for sles12, I guess you need to specify only the min protocol or else it defaults to SMBv2. You may have to play with the configurations with other flavors of linux just to ensure that SMBv2 connections are accepted.

SmbConfig config=SmbConfig.builder().withMultiProtocolNegotiate(true).withSigningRequired(false).build(); --> This will help you identify if your samba server accepts SMBv2 connections. 

With all this in place, my setup worked fine for both guest and anonymous authentication.

**Comment by debarghya85** [comment] 2017-10-17 11:28
Thanks. I will check.

**Comment by hierynomus** [comment] 2017-10-23 09:50
@debarghya85 Any update?

**Comment by hierynomus** [comment] 2017-11-14 10:07
@debarghya85 Were you able to solve this using the answers provided?

**Comment by hierynomus** [comment] 2017-11-21 13:10
@debarghya85 Can this be closed?

**Comment by Varsha-Nagarajan** [comment] 2017-11-21 13:14
Based on the settings I have provided earlier, this case should work. I
have tested it and it works perfectly for me. So I guess we can close this
issue.

**Comment by debarghya85** [comment] 2017-11-22 08:42
Please close this.

**Closed** 2017-11-22 09:12 UTC
Labels: question
