### ISSUE TITLE
DiskShare.getFileInformation() does not work properly for root directory

### ISSUE THREAD

**Issue by swtet2003** [hierynomus/smbj#80] opened 2017-06-14 20:15 UTC
We built a version of SMBJ when this was the head of master:

https://github.com/hierynomus/smbj/commit/57dfc9825b6d0f4935cf787e4fba8ac1ce7e9632

With that code, the following code snippet would report inconsistent results between Windows 10 and Windows Server 2012.  For Win 10, the name information was "".  For 2012, it was "\temp".  Both hosts negotiated SMB_2_1 dialect.

DiskShare share = (DiskShare)session.connectShare( "temp" );
FileAllInformation file = share.getFileInformation( "" );
System.out.println( "File info name: " + file.getNameInformation() );

I just rebuilt today what is in master (hoping that the issue had already been resolved) and now using "" or even null does not work.  I get the following error, using "":

com.hierynomus.smbj.common.SMBApiException: STATUS_SHARING_VIOLATION(3221225539/3221225539): Create failed for
        at com.hierynomus.smbj.share.Share.receive(Share.java:219)
        at com.hierynomus.smbj.share.Share.sendReceive(Share.java:198)
        at com.hierynomus.smbj.share.Share.createFile(Share.java:115)
        at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:64)
        at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:60)
        at com.hierynomus.smbj.share.DiskShare.getFileInformation(DiskShare.java:159)
        at com.hierynomus.smbj.share.DiskShare.getFileInformation(DiskShare.java:152)

Any idea how I can resolve either of these issues?

**Comment by pepijnve** [comment] 2017-06-15 06:26
This is due to the code path that accepts a string path not specifying any share modes. It used to specify all in earlier versions. I'll fix that asap.
If you need a short term workaround, you can fix this by using `openDirectory` with access mask `GENERIC_READ`, a set of all the ShareAccess values and create disposition `FILE_OPEN`. Then call `getFileInformation` on the returned Directory object followed by `close`.

**Comment by hierynomus** [comment] 2017-06-15 10:44
Fixed with merging #81

**Comment by swtet2003** [comment] 2017-06-15 13:08
Any chance you can update SMBTest to reflect the API changes?

With the changes that were merged to master, I am back to my original problem where Win 10 and 2012 report different information using DiskShare.getFileInformation().  Any idea how to fix that?

**Comment by pepijnve** [comment] 2017-06-15 13:13
SMBJ just passes on what it receives from the server. Different SMB servers behave differently in corner cases of the specification. Not much that can be done about that in a client library I think.

**Comment by swtet2003** [comment] 2017-06-15 13:20
As a consumer of the client library, that forces me to understand the differences in the SMB spec and code around it based on the host that I am connecting to...seems like that should be a library concern.

**Comment by pepijnve** [comment] 2017-06-15 13:24
I'll leave it to @hierynomus to make that philosophical decision 😄 
My opinion is that an SMB client library should not manipulate requests/responses on the users behalf. Adding these kinds of workarounds is a rabbit hole. There's no way to get things consistent across every single file server.

Could you explain why this matters for your use case? Perhaps there's a different way to get the information you need that doesn't required these workarounds.

**Comment by hierynomus** [comment] 2017-06-15 13:29
Yes, I would be interested in knowing what the difference is :)

2017-06-15 15:24 GMT+02:00 Pepijn Van Eeckhoudt <notifications@github.com>:

**Comment by swtet2003** [comment] 2017-06-15 14:30
I am trying to get the entries name.  If it is the root of the share, I could understand "" or even "." maybe.  Besides being inconsistent, it also appears to be wrong or, I should be doing something else.  If I pass a path into getFileInformation( "dir\file.txt" ), on Win 10, I always get "" from getNameInformation().  On 2012, I would get "\temp\dir\file.txt".  I wasn't expecting a full path but at least I could deal with that.  With Win 10 always being an empty string, that seems wrong.

**Comment by pepijnve** [comment] 2017-06-15 14:31
I'll check with my Windows 10 VM in a minute. But you should be blaming Windows 10; not SMBJ.

**Comment by pepijnve** [comment] 2017-06-15 15:08
FWIW I can confirm that Windows 10 sends back empty names.

@hierynomus this is what I'm getting back from the SMB server on a GETINFO request for FileAllInformation on a file named "Test.txt". You can see in the last line that filename length is 0. This results in an empty string as filename. Perhaps `null` would be more correct here?

```
SMB2 (Server Message Block Protocol version 2)
    SMB2 Header
        Server Component: SMB2
        Header Length: 64
        Credit Charge: 1
        NT Status: STATUS_SUCCESS (0x00000000)
        Command: GetInfo (16)
        Credits granted: 2
        Flags: 0x00000009, Response, Signing
        Chain Offset: 0x00000000
        Message ID: 8
        Process Id: 0x00000000
        Tree Id: 0x00000001  \\172.16.88.186\WideOpen
        Session Id: 0x000018000000000d Acct:pepijn Domain: Host:
        Signature: 31278b37512ea8b070951fe992d87d8d
        [Response to: 32]
        [Time from request: 0.000307000 seconds]
    GetInfo Response (0x10)
        [Class: FILE_INFO (0x01)]
        [InfoLevel: SMB2_FILE_ALL_INFO (0x12)]
        StructureSize: 0x0009
        Offset: 0x00000048
        Length: 104
        SMB2_FILE_ALL_INFO
            Create: Mar 21, 2017 11:29:53.924312000 CET
            Last Access: Mar 21, 2017 11:29:53.924312000 CET
            Last Write: Mar 21, 2017 11:29:53.924312000 CET
            Last Change: Jun 15, 2017 16:44:19.413127200 CEST
            File Attributes: 0x00000020
            unknown: 00000000
            Allocation Size: 0
            End Of File: 0
            Number of Links: 1
            Delete Pending: 0
            Is Directory: 0
            File Id: 0x0031000000000e35
            EA Size: 0
            Access Mask: 0x00120089
            unknown: 00000000000000000000000000000000
            Filename Length: 0
```

I was able to get the name out using a directory query. This isn't in the API yet, but I extended list to allow you to specify the search pattern parameter.

The direct query returns the reply above
```
FileAllInformation allInfo = share.getFileInformation("Test.txt");
System.out.println("Name: '" + allInfo.getNameInformation() + "'");
```

A directory query for names information with a search pattern of the file name does return the name.
```
List<FileNamesInformation> list = share.list("", "Test.txt", FileNamesInformation.class);
for (FileNamesInformation fileNamesInformation : list) {
  System.out.println("Name: '" + fileNamesInformation.getFileName() + "'");
}
```

I'll create a PR for this directory listing enhancement.

**Comment by swtet2003** [comment] 2017-06-16 13:49
Going back to a previous comment, I am beginning to wonder if getFileInformation() is not what I need in my situation.  I am trying to find basic information about a file/directory: type (file or directory), name, size, create date, modify date.  As we have been discussing, the name information has issues.  Now I can't seem to find a way to get the file size.  I can get the allocation size but that is not what I need.  Is there a better way to get all of this information or am I just missing something?

**Comment by pepijnve** [comment] 2017-06-16 13:51
Well, the name you kind of already have since you need to pass that in as a parameter. The file size is in `FileStandardInformation#endOfFile`. Timestamps and attributes are all in `FileBasicInformation`.

**Comment by swtet2003** [comment] 2017-06-16 13:57
I do kind of have the name....I pass in a full path, which includes the name.  But, I don't necessarily have the proper case, which would be nice to get (somefile.txt == SomeFile.txt).  I would have never guessed endOfFile().  You might want to rename that or at least JavaDoc it.

**Comment by pepijnve** [comment] 2017-06-16 13:59
Regarding the semantics of the information classes and fields, best to read the docs https://msdn.microsoft.com/en-us/library/cc232088.aspx

**Comment by hierynomus** [comment] 2017-06-22 13:14
See the discussion in #84.

Last comment by me in that thread: Unless you can come up with a very good solution for how to fix the fact that the server omits information, I would also not be inclined to add something like that.

What I can imagine is adding a quirks/compatibility mode which you could set in the config. For instance `config.setQuirksMode(SmbQuirks.Win10)`, but then what should it do in that case for this specific problem? It's not like it can come up with a filename out of thin air....

**Comment by hierynomus** [comment] 2023-03-19 20:02
Closing this, currently we won't be dealing with this quirk.

**Closed by hierynomus** 2023-03-19 20:02 UTC
Labels: enhancement
