### ISSUE TITLE
STATUS_ACCESS_DENIED (0xc0000022)

### ISSUE THREAD

**Issue by RomanKarpliak96** [hierynomus/smbj#355] opened 2018-07-10 10:31 UTC
We had STATUS_ACCESS_DENIED(3221225506/3221225506) when trying to write a file on a share.
After updating library to 0.7.1-SNAPHOT  which was built from issue-328 branch we see another error.
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Create failed for \\SERVER\share\ESHSTIMP
	at com.hierynomus.smbj.share.Share.receive(Share.java:342)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:322)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:135)
	at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:94)
	at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:87)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:67)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:160)

Could someone help with this issue?

**Comment by hierynomus** [comment] 2018-07-10 10:40
You might want to provide a bit more context

**Comment by RomanKarpliak96** [comment] 2018-07-10 10:48
@hierynomus , updated previous comment with information

**Comment by pepijnve** [comment] 2018-07-10 11:16
The error `STATUS_ACCESS_DENIED` is returned by the server and means what it says: the user that's logged in to the server is not being granted the requested access to the file or directory in question. This is not an SMBJ library issue.

**Comment by RomanKarpliak96** [comment] 2018-07-10 11:45
I can confirm that user connected to share has all privileges to create file.
We use administrattor account and can create a file directly on share.

![image](https://user-images.githubusercontent.com/41054638/42508012-c2d2cf32-844f-11e8-8185-e02608b7f254.png)

**Comment by pepijnve** [comment] 2018-07-10 11:51
Have a look at https://docs.microsoft.com/en-us/windows/desktop/FileIO/creating-and-opening-files. That explains Windows/SMB access masks in detail.

What are you specifying as desired access?  You're probably requesting something that's not being allowed by the server. Try opening the file with MAXIMUM_ALLOWED for instance, does that work?

**Comment by RomanKarpliak96** [comment] 2018-07-10 12:31
thank you, @pepijnve. With MAXIMUM_ALLOWED it works.

**Comment by pepijnve** [comment] 2018-07-10 12:33
Ok, so now your code is telling the server: grant me whatever permissions I'm allowed to get. If that's what you want then you're done. Otherwise, try specifying the minimal set of access flags that you actually need.
What were you requesting before?

Anyway, as stated earlier this is simply how the SMB protocol works. Could you close this issue since it's not a bug?

**Comment by hierynomus** [comment] 2018-07-10 12:33
Ok, closing the issue.

**Closed** 2018-07-10 12:33 UTC
