### ISSUE TITLE
this project is just smb client? can I  achieve smb server with it.

### ISSUE THREAD

**Issue by huanyuan** [hierynomus/smbj#472] opened 2019-05-29 02:35 UTC

**Comment by hierynomus** [comment] 2019-05-29 08:01
At this moment there is no concrete plan to implement a server, though a lot of the groundwork for that is shared. I'll keep this issue around and I will consider it

**Comment by hierynomus** [comment] 2022-02-18 14:34
Duplicate of #209. Closing this in favour of that.

**Closed by hierynomus** 2022-02-18 14:34 UTC
