### ISSUE TITLE
Getting IOException before building project

### ISSUE THREAD

**Issue by damaro333** [hierynomus/smbj#360] opened 2018-07-17 09:16 UTC
Hello,

I am new at Android coding. But I made a project for Android in Android Studio.
When copying the example code the section client.connect("hostname") gets underlined and it says "Unhandled Exception: java.io.IOException" and the second try block says the same. 

Any ideas?

Adobe SDK 28, Build Tools Version 28.0.1

`        SMBClient client = new SMBClient();
        try (Connection connection = client.connect("hostname")) {
            AuthenticationContext ac = new AuthenticationContext("user", "pw".toCharArray(), "ip");
            Session session = connection.authenticate(ac);

//             Connect to Share
            try (DiskShare share = (DiskShare) session.connectShare("SHARENAME")) {
                for (FileIdBothDirectoryInformation f : share.list("FOLDER", "*.TXT")) {
                    System.out.println("File : " + f.getFileName());
                }
            }
        }`

**Comment by pepijnve** [comment] 2018-07-17 09:19
Hi @damaro333,

I understand your problem is caused by code that uses the smbj library, but this question is a very basic Java programming one; nothing to do with the library itself. This is not the appropriate place to ask this type of question.

Have a look at the Java documentation on exception handling at https://docs.oracle.com/javase/tutorial/essential/exceptions/index.html. In a nutshell, `IOException` is a checked exception, meaning you either need to declare that your method throws it or handle it in a catch block.

**Comment by damaro333** [comment] 2018-07-17 09:22
Hi @pepijnve 

The IOException is throwed through the smbj lib? The connect function says "public Connection connect(String hostname) throws IOException", thats why I don't know what to do now.

**Comment by pepijnve** [comment] 2018-07-17 09:23
I hate to be rude, but this is really not the place to ask Java programming 101 questions. Please read the documentation or any tutorial on Java exception handling.

**Comment by pepijnve** [comment] 2018-07-17 09:34
Seriously... What you're asking amounts to asking people to teach you how to program Java. For free. This is a trivial compilation error. The compiler is telling you exactly what the problem is. I point you to the relevant documentation that explains how Java exceptions work and the difference between checked and unchecked exceptions. And you refuse to even read the documentation.
Sorry, but you've kind of used up my goodwill http://lmgtfy.com/?q=Unhandled+Exception%3A+java.io.IOException

**Comment by hierynomus** [comment] 2018-07-17 11:03
Closing this. I suggest you read up on Java programming and exception handling.

If you're wondering _why_ the IOException is being thrown: We need to connect a Java socket to transmit data to the remote party. As part of connecting to a socket, an IOException could be thrown in case the network connection could not be established.

**Closed by hierynomus** 2018-07-17 11:03 UTC
