### ISSUE TITLE
how can i stop the default logging in the smbj because i am using my own logging framework 

### ISSUE THREAD

**Issue by rahulgangarde** [hierynomus/smbj#313] opened 2018-04-16 11:58 UTC

**Comment by pepijnve** [comment] 2018-04-16 13:00
The library uses slf4j. Please refer to the documentation of that library for details on how to control logging output. (https://www.slf4j.org/manual.html)

**Comment by hierynomus** [comment] 2018-04-24 11:07
@rahulgangarde Did this answer your question?

**Comment by hierynomus** [comment] 2018-05-03 20:42
Closing as this has been answered

**Closed by hierynomus** 2018-05-03 20:42 UTC

**Comment by timautin** [comment] 2020-02-19 10:26
For anyone coming here:

Add a simplelogger.properties file in your resources directory, and in this file write:

# App logging level:
org.slf4j.simpleLogger.defaultLogLevel=info

# Disable SMBJ logging:
org.slf4j.simpleLogger.log.com.hierynomus=off

**Comment by bb8-droid** [comment] 2020-06-15 07:13
> 
> 
> For anyone coming here:
> 
> Add a simplelogger.properties file in your resources directory, and in this file write:
> 
> ```
> # App logging level:
> org.slf4j.simpleLogger.defaultLogLevel=info
> 
> # Disable SMBJ logging:
> org.slf4j.simpleLogger.log.com.hierynomus=off
> ```

This does not work for me. Still getting all log messages.

**Comment by ecki** [comment] 2020-06-15 11:06
Maybe you have a different log4j backend in your classpath which is configured differently?

**Comment by bb8-droid** [comment] 2020-06-15 14:34
> 
> 
> Maybe you have a different slf4j backend in your classpath which is configured differently?

Thank you! That was the right idea. I removed this from my .pom and now it works.

		<dependency>
		    <groupId>ch.qos.logback</groupId>
		    <artifactId>logback-classic</artifactId>
		    <version>1.2.3</version>
		    <scope>test</scope>
		</dependency>

**Comment by Jaawn** [comment] 2022-08-04 18:23
I have been running into this issue for awhile and a Google search landed me here. In case anyone else out there is in a similar situation: I believe the root cause in my case stems from running the application using IBM Java and/or IBM WebSphere libraries, but nothing I tried would modify whatever backend SLF4J configuration was being used (there seems to be a binding included in one of the WebSphere libraries). However, I found that whatever it is must be binding to JUL because setting the JUL level allowed me to control the SMBJ log output. For example, setting the root logger level like this:
`java.util.logging.LogManager.getLogger("").setLevel(Level.WARNING);`
also affected SMBJ logging. So, anyone struggling with this may need to look through dependencies for a badly-behaved library which is pulling in a specific logger binding in order to sort this out.
